---
title: "git_01"
author: "Jason Rivera"
date: "September 9th, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse
'Twas brillig, and the slithy toves   
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
'Beware the Jabberwock, my son!  
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
He saw her from the bottom of the stairs  
Before she saw him.  She was starting down,  
Looking back over her shoulder at some fear.  
She took a doubtful step and then undid it  
To raise herself and look again.  He spoke  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->The sun was shining on the sea,  
      Shining with all his might:  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->You may write me down in history  
With your bitter, twisted lies,  
You may tread me in the very dirt  
But still, like dust, I'll rise.  

Does my sassiness upset you?  
Why are you beset with gloom?  
'Cause I walk like I've got oil wells  
Pumping in my living room.  

Just like moons and like suns,  
With the certainty of tides,  
Just like hopes springing high,  
Still I'll rise.  

Did you want to see me broken?  
Bowed head and lowered eyes?  
Shoulders falling down like teardrops.  
Weakened by my soulful cries.  

Does my haughtiness offend you?  
Don't you take it awful hard  
'Cause I laugh like I've got gold mines  
Diggin' in my own back yard  
